/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateLayoutRouteImport } from './routes/(private)/_layout'
import { Route as privateIndexRouteImport } from './routes/(private)/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as privateContratosNovoIndexRouteImport } from './routes/(private)/contratos/novo/index'

const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateContratosNovoIndexRoute =
  privateContratosNovoIndexRouteImport.update({
    id: '/contratos/novo/',
    path: '/contratos/novo/',
    getParentRoute: () => privateLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof privateIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/contratos/novo': typeof privateContratosNovoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof privateIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/contratos/novo': typeof privateContratosNovoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(private)/': typeof privateIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/(private)/contratos/novo/': typeof privateContratosNovoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login' | '/contratos/novo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/contratos/novo'
  id:
    | '__root__'
    | '/(private)'
    | '/(private)/'
    | '/auth/login/'
    | '/(private)/contratos/novo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/contratos/novo/': {
      id: '/(private)/contratos/novo/'
      path: '/contratos/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof privateContratosNovoIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface privateLayoutRouteChildren {
  privateIndexRoute: typeof privateIndexRoute
  privateContratosNovoIndexRoute: typeof privateContratosNovoIndexRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateIndexRoute: privateIndexRoute,
  privateContratosNovoIndexRoute: privateContratosNovoIndexRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
